## python libraries


### create 1d array

In [16]:
import numpy as np
x=np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


### create 2d array

In [27]:
y=np.array([[1,2,3],[1,2,3]])
print(y)

[[1 2 3]
 [1 2 3]]


In [40]:
a=[[1,2,3],[1,2,3],[1,2,3]]
s=np.array(a)
print(s)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
s.ndim

2

In [45]:
s.shape

(3, 3)

### create 3d array

In [48]:
z=np.array([[[1,2],[2,2],[1,3]],[[1,1],[2,3],[3,4]]])
print(z)

[[[1 2]
  [2 2]
  [1 3]]

 [[1 1]
  [2 3]
  [3 4]]]


In [50]:
print(z[0])

[[1 2]
 [2 2]
 [1 3]]


In [51]:
print(z[0][0])

[1 2]


In [52]:
z[0][0][0]

1

In [53]:
z[1]

array([[1, 1],
       [2, 3],
       [3, 4]])

In [54]:
z.ndim

3

In [49]:
z.shape

(2, 3, 2)

In [55]:
z.size

12

### complex values

In [56]:
p=np.array([1,2,3],dtype=complex)
print(p)

[1.+0.j 2.+0.j 3.+0.j]


In [57]:
a=[[1,2,3],[1,2,3]]
print(a)

[[1, 2, 3], [1, 2, 3]]


### array slicing

In [61]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
print(x[0:5])

[0 1 2 3 4]


In [69]:
x[:6:2]

array([0, 2, 4])

In [70]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [71]:
x[5::-2]

array([5, 3, 1])

### reshaping of arrays

In [76]:
s=np.arange(1,9).reshape(2,2,2)
print(s)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### concatination of arrays

In [78]:
x=np.array([1,2,3])
y=np.array([4,3,2])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 3 2]


In [79]:
z[1]+z[2]

5

### spliting of arrays

In [80]:
a,b=np.split(z,[3])
print(a)
print(b)

[1 2 3]
[4 3 2]


## task

In [87]:
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
a=np.arange(10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [90]:
a.reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [91]:
a.reshape(10,10,10,10)

array([[[[   0,    1,    2, ...,    7,    8,    9],
         [  10,   11,   12, ...,   17,   18,   19],
         [  20,   21,   22, ...,   27,   28,   29],
         ...,
         [  70,   71,   72, ...,   77,   78,   79],
         [  80,   81,   82, ...,   87,   88,   89],
         [  90,   91,   92, ...,   97,   98,   99]],

        [[ 100,  101,  102, ...,  107,  108,  109],
         [ 110,  111,  112, ...,  117,  118,  119],
         [ 120,  121,  122, ...,  127,  128,  129],
         ...,
         [ 170,  171,  172, ...,  177,  178,  179],
         [ 180,  181,  182, ...,  187,  188,  189],
         [ 190,  191,  192, ...,  197,  198,  199]],

        [[ 200,  201,  202, ...,  207,  208,  209],
         [ 210,  211,  212, ...,  217,  218,  219],
         [ 220,  221,  222, ...,  227,  228,  229],
         ...,
         [ 270,  271,  272, ...,  277,  278,  279],
         [ 280,  281,  282, ...,  287,  288,  289],
         [ 290,  291,  292, ...,  297,  298,  299]],

        ...,

  

In [119]:
a=np.ones((3,3,3),int)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [120]:
l=a-1

In [121]:
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [122]:
a=np.zeros((3,2,1),int,"F")
a

array([[[0],
        [0]],

       [[0],
        [0]],

       [[0],
        [0]]])

In [123]:
a=np.ones((3,2,1),int,"C")
a

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [124]:
print(np.sqrt(a))

[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]]


In [125]:
print(np.sin(l))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [126]:
np.sin(a)

array([[[0.84147098],
        [0.84147098]],

       [[0.84147098],
        [0.84147098]],

       [[0.84147098],
        [0.84147098]]])

In [127]:
np.log(a)

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [128]:
x=np.random.rand(2,5)

In [129]:
x

array([[0.32567558, 0.46295774, 0.66693522, 0.51219163, 0.52030296],
       [0.92956739, 0.67262274, 0.93286679, 0.40272219, 0.00287966]])

In [155]:
x=np.random.randint(5,size=10)

In [150]:
x

array([2, 3, 4, 1, 0, 4, 1, 4, 2, 2])

In [156]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [157]:
print(len(dir(np)))

620


In [158]:
np.__version__

'1.19.2'

### filtering array

In [161]:
import numpy as np
ary=np.array([1,2,3,4,5])
x=[True,False,True,False,True]
nary=ary[x]
print(nary)

[1 3 5]


In [162]:
a=np.array([1,2,3])
f=a%2==0
n=a[f]
print(n)
print(f)

[2]
[False  True False]


In [163]:
a=np.array([1,2,4])
f=a%2==1
n=a[f]
print(n)
print(f)

[1]
[ True False False]


### statistical

In [164]:
q=np.array([[3,7,5],[2,3,4]])
q

array([[3, 7, 5],
       [2, 3, 4]])

In [165]:
print(np.amax(q,1))

[7 4]


In [166]:
print(np.amax(q,1))
print(np.amax(q,0))
print(np.amin(q,1))
print(np.amin(q,0))

[7 4]
[3 7 5]
[3 2]
[2 3 4]
